steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - ${_AR_HOSTNAME}/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID
      - .
      - -f
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --platform=managed
      - --image=${_AR_HOSTNAME}/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID
      - --region=${_DEPLOY_REGION}
      - --memory=2Gi
      - --cpu=2
      - --timeout=3600
      - --max-instances=3
      - --allow-unauthenticated
      - --set-env-vars=RUNNING_IN_CLOUD=True,ENVIRONMENT=production,API_ID=30643078,DATABASE_URL=bot_database.db,TURSO_DATABASE_URL=libsql://oisha-os-db-baxtiyorjongaziyev.turso.io,AMOCRM_SUBDOMAIN=jonbrandingagency,AMOCRM_CLIENT_ID=5a755b58-f5d1-477d-965d-a50ddaa3d55e,AMOCRM_REDIRECT_URL=https://us-central1-jonbranding-85662071-ea38e.cloudfunctions.net/amocrmOAuthCallback,AIRTABLE_BASE_ID=app8xoyx1XCumYFXV,CRM_GROUP_ID=-1002566480563,CRM_TOPIC_ID=,TEAM_GROUP_ID=-4860594772,TOPIC_KIRIM_ID=168,GSHEET_ID=1KEFClhl4mVwCXI3YPfeE1B9X3SOkML2fp3NMocZzm8k,GSHEET_CREDS_FILE=service_account.json,OWNER_ID=150074828
      - --set-secrets=API_HASH=oisha-api-hash:latest,BOT_TOKEN=oisha-bot-token:latest,GEMINI_API_KEY=oisha-gemini-api-key:latest,DEEPSEEK_API_KEY=oisha-deepseek-api-key:latest,TURSO_AUTH_TOKEN=oisha-turso-auth-token:latest,AMOCRM_CLIENT_SECRET=oisha-amocrm-client-secret:latest,AIRTABLE_API_KEY=oisha-airtable-api-key:latest,USERBOT_SESSION_B64=oisha-userbot-session-b64:latest,GOOGLE_SERVICE_ACCOUNT_JSON=oisha-google-service-account-json:latest
      - --quiet

images:
  - ${_AR_HOSTNAME}/$PROJECT_ID/${_AR_REPOSITORY}/${_SERVICE_NAME}:$BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _AR_HOSTNAME: europe-west3-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: europe-west3
  _SERVICE_NAME: oisha-master-bot
