# fly.toml app configuration file generated for oisha-os on 2026-07-15T17:51:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oisha-os'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'
  RUNNING_IN_CLOUD = 'True'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/system/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
