import pytest
from unittest.mock import AsyncMock, MagicMock, patch
from src.database_pool import SmartRow
from src.services.core.ambassador_journey import AmbassadorJourneyManager


class MockCursor:
    """
    A unified mock helper that behaves exactly like an aiosqlite Cursor:
    1. Can be awaited directly: `cursor = await conn.execute(...)`
    2. Can be used as an async context manager: `async with conn.execute(...) as cursor:`
    """
    def __init__(self, fetch_val=None, fetchall_val=None):
        self.fetch_val = fetch_val
        self.fetchall_val = fetchall_val

    def __await__(self):
        async def _async_self():
            return self
        return _async_self().__await__()

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        pass

    async def fetchone(self):
        return self.fetch_val

    async def fetchall(self):
        return self.fetchall_val


def _mock_db_conn(fetch_val=None, fetchall_val=None):
    cursor = MockCursor(fetch_val=fetch_val, fetchall_val=fetchall_val)

    mock_conn = MagicMock()
    # execute returns the cursor (which is both awaitable and an async context manager)
    mock_conn.execute = MagicMock(return_value=cursor)
    mock_conn.commit = AsyncMock()

    db_mock = MagicMock()
    db_mock.get_connection = AsyncMock(return_value=mock_conn)
    return db_mock, mock_conn, cursor


@pytest.mark.asyncio
async def test_sync_won_leads_to_ambassadors_success():
    amocrm_mock = MagicMock()
    
    # 1 won deal (142), 1 open deal (100)
    mock_leads = [
        {
            "id": 111,
            "status_id": 142,
            "name": "Branding for TestCorp",
            "_embedded": {
                "contacts": [
                    {
                        "name": "Akmal",
                        "custom_fields_values": [
                            {
                                "field_code": "PHONE",
                                "values": [{"value": "+998901234567"}]
                            }
                        ]
                    }
                ]
            }
        },
        {"id": 222, "status_id": 100, "name": "Strategy for OpenCorp"}
    ]
    amocrm_mock.get_leads_detailed = AsyncMock(return_value=mock_leads)
    
    # DB Mock where _has_nps_scheduled returns None (False)
    db_mock, mock_conn, mock_cursor = _mock_db_conn(fetch_val=None)
    db_mock.update_lead_journey = AsyncMock(return_value=True)
    db_mock.get_user_id_by_phone = AsyncMock(return_value=111)

    manager = AmbassadorJourneyManager(amocrm=amocrm_mock, db=db_mock, gemini_api_key="mock_key")

    with patch.object(manager, "generate_nps_survey_text", return_value="NPS matni"):
        stats = await manager.sync_won_leads_to_ambassadors(limit=10)
        assert stats["synced"] == 1
        assert stats["errors"] == 0
        
        # Check that update_lead_journey was called for the won deal
        db_mock.update_lead_journey.assert_called_once_with(
            user_id=111,
            stage="Ambassador",
            status="active",
            next_action="Send NPS Survey",
            close_probability=100.0,
        )


@pytest.mark.asyncio
async def test_generate_nps_survey_text_gemini_success():
    amocrm_mock = MagicMock()
    db_mock = MagicMock()

    manager = AmbassadorJourneyManager(amocrm=amocrm_mock, db=db_mock, gemini_api_key="mock_key")
    
    # Mock Gemini AI response
    mock_response = MagicMock()
    mock_response.text = "Custom warm Uzbek NPS text generated by Gemini"
    
    manager.genai_client = MagicMock()
    manager.genai_client.aio = MagicMock()
    manager.genai_client.aio.models = MagicMock()
    manager.genai_client.aio.models.generate_content = AsyncMock(return_value=mock_response)

    survey_text = await manager.generate_nps_survey_text(
        client_name="Toshmat", brand_name="Elite Brand", service_type="Design"
    )
    
    assert "Custom warm Uzbek NPS text" in survey_text
    manager.genai_client.aio.models.generate_content.assert_called_once()
    assert (
        manager.genai_client.aio.models.generate_content.call_args.kwargs["model"]
        == "gemini-2.5-flash"
    )


@pytest.mark.asyncio
async def test_process_scheduled_touchpoints_via_userbot():
    amocrm_mock = MagicMock()
    userbot_mock = MagicMock()

    # DB Mock for pending logs
    pending_row = SmartRow(
        [42, 111222, 5555, "nps_survey", "Assalomu alaykum Toshmat aka!"],
        ["id", "user_id", "lead_id", "touchpoint_type", "sent_message"],
    )
    resolved_user = SmartRow(
        ["toshmat_username", "+998901234567"],
        ["username", "phone"],
    )
    db_mock, mock_conn, mock_cursor = _mock_db_conn(fetch_val=resolved_user, fetchall_val=[pending_row])

    manager = AmbassadorJourneyManager(
        amocrm=amocrm_mock, db=db_mock, user_client=userbot_mock, gemini_api_key="mock_key"
    )

    # Mock userbot resolving and sending
    userbot_mock.get_input_entity = AsyncMock(return_value="toshmat_peer_id")
    userbot_mock.send_message = AsyncMock()

    stats = await manager.process_scheduled_touchpoints()
    
    assert stats["sent"] == 1
    assert stats["failed"] == 0
    
    # Assert Telegram message sent
    userbot_mock.send_message.assert_called_once_with("toshmat_peer_id", "Assalomu alaykum Toshmat aka!")
