import sys
import importlib
import logging

logger = logging.getLogger(__name__)

# Oisha-OS Bosqich 3 Re-export Map
_MODULE_MAP = {
    'enterprise_reporter': '.reporting.enterprise_reporter',
    'audit_agent': '.reporting.audit_agent',
    'case_publisher': '.reporting.case_publisher',
    'sanity_publisher': '.reporting.sanity_publisher',
    'sales_analytics': '.reporting.sales_analytics',
    'tez_natija_exporter': '.reporting.tez_natija_exporter',
    'instagram_weekly_report': '.reporting.instagram_weekly_report',
    'pipeline_auditor': '.reporting.pipeline_auditor',
    'advisor_agent': '.ai.advisor_agent',
    'call_analyzer': '.ai.call_analyzer',
    'contact_intro_parser': '.ai.contact_intro_parser',
    'deal_ai_analyzer': '.ai.deal_ai_analyzer',
    'escalation_agent': '.ai.escalation_agent',
    'ltv_predictor': '.ai.ltv_predictor',
    'ltv_trainer': '.ai.ltv_trainer',
    'self_evolution': '.ai.self_evolution',
    'self_improvement': '.ai.self_improvement',
    'self_improvement_agent': '.ai.self_improvement_agent',
    'self_learning': '.ai.self_learning',
    'userbot_learner': '.ai.userbot_learner',
    'activity_monitor': '.diagnostics.activity_monitor',
    'oisha_self_diagnosis': '.diagnostics.oisha_self_diagnosis',
    'evolution_scheduler': '.diagnostics.evolution_scheduler',
    'monitor_resources': '.diagnostics.monitor_resources',
    'sla_monitor': '.diagnostics.sla_monitor',
    'session_keeper': '.diagnostics.session_keeper',
    'retry_queue': '.diagnostics.retry_queue',
    'agency_personas': '.agency.agency_personas',
    'project_phases': '.agency.project_phases',
    'business_command_center': '.agency.business_command_center',
    'client_checklist': '.agency.client_checklist',
    'client_project_checklist': '.agency.client_project_checklist',
    'hr_engine': '.agency.hr_engine',
    'oisha_product_suite': '.agency.oisha_product_suite',
    'persona_hub': '.agency.persona_hub',
    'project_engine': '.agency.project_engine',
    'rnp_research': '.agency.rnp_research',
    'wow_service_engine': '.agency.wow_service_engine',
    'admin_aiogram_dispatcher': '.comms.admin_aiogram_dispatcher',
    'admin_bot': '.comms.admin_bot',
    'admin_command_router': '.comms.admin_command_router',
    'auto_reply_gate': '.comms.auto_reply_gate',
    'bot_to_bot': '.comms.bot_to_bot',
    'channel_scheduler': '.comms.channel_scheduler',
    'channel_scout': '.comms.channel_scout',
    'chat_bridge': '.comms.chat_bridge',
    'guest_bot': '.comms.guest_bot',
    'instagram_agent': '.comms.instagram_agent',
    'proactive_worker': '.comms.proactive_worker',
    'safe_responder': '.comms.safe_responder',
    'sms_gateway_client': '.comms.sms_gateway_client',
    'telegram_session_manager': '.comms.telegram_session_manager',
    'uzbek_telegram_scraper': '.comms.uzbek_telegram_scraper',
    'uzbek_instagram_scraper': '.comms.uzbek_instagram_scraper',
    'uzbek_linkedin_scraper': '.comms.uzbek_linkedin_scraper',
    'voice_agent': '.comms.voice_agent',
    'uzbek_voice_agent': '.comms.uzbek_voice_agent',
    'workflow_telegram_bot': '.comms.workflow_telegram_bot',
    'agent_loop': '.agent.agent_loop',
    'agent_policy': '.agent.agent_policy',
    'agent_verifier': '.agent.agent_verifier',
    'agent_brain': '.agent.agent_brain',
    'agent_runtime': '.agent.agent_runtime',
    'agent_orchestrator': '.agent.agent_orchestrator',
    'tool_registry': '.agent.tool_registry',
    'tool_adapters': '.agent.tool_adapters',
    'oisha_coordinator': '.agent.oisha_coordinator',
    'oisha_memory': '.agent.oisha_memory',
    'mission_control': '.agent.mission_control',
    'airtable_client': '.integrations.airtable_client',
    'airtable_sync': '.integrations.airtable_sync',
    'apollo_enrich': '.integrations.apollo_enrich',
    'composio_tasks': '.integrations.composio_tasks',
    'docusign_sync': '.integrations.docusign_sync',
    'gcalendar': '.integrations.gcalendar',
    'gcontacts': '.integrations.gcontacts',
    'gdrive': '.integrations.gdrive',
    'github_manager': '.integrations.github_manager',
    'google_service': '.integrations.google_service',
    'gsheets': '.integrations.gsheets',
    'salescoach_sync': '.integrations.salescoach_sync',
    'uzbek_integrations': '.integrations.uzbek_integrations',
    'action_parser': '.tasks.action_parser',
    'auto_execution': '.tasks.auto_execution',
    'auto_task_creator': '.tasks.auto_task_creator',
    'checklist_manager': '.tasks.checklist_manager',
    'daily_enforcer': '.tasks.daily_enforcer',
    'historical_sync': '.tasks.historical_sync',
    'juma_notifier': '.tasks.juma_notifier',
    'mandatory_workflow': '.tasks.mandatory_workflow',
    'night_shift': '.tasks.night_shift',
    'service_configurator': '.tasks.service_configurator',
    'smart_task_creator': '.tasks.smart_task_creator',
    'workflow_manager': '.tasks.workflow_manager',
    'workflow_orchestrator': '.tasks.workflow_orchestrator',
    'ambassador_journey': '.sales.ambassador_journey',
    'auto_lead_agent': '.sales.auto_lead_agent',
    'callmaster_service': '.sales.callmaster_service',
    'channel_lead_extractor': '.sales.channel_lead_extractor',
    'client_journey_playbook': '.sales.client_journey_playbook',
    'deal_hygiene': '.sales.deal_hygiene',
    'manager_nagger': '.sales.manager_nagger',
    'meeting_scheduler': '.sales.meeting_scheduler',
    'sales_coach': '.sales.sales_coach',
    'sales_playbook': '.sales.sales_playbook',
    'sales_quality_coach': '.sales.sales_quality_coach',
    'uzbek_call_queue': '.sales.uzbek_call_queue',
    'uzbek_entrepreneurs_handler': '.sales.uzbek_entrepreneurs_handler',
    'uzbek_entrepreneurs_schema': '.sales.uzbek_entrepreneurs_schema',
    'uzbek_entrepreneurs_scraper': '.sales.uzbek_entrepreneurs_scraper',
    'hisobchi_analyst': '.hisobchi.hisobchi_analyst',
    'hisobchi_approval': '.hisobchi.hisobchi_approval',
    'hisobchi_gsheets': '.hisobchi.hisobchi_gsheets',
    'hisobchi_mcp': '.hisobchi.hisobchi_mcp',
    'hisobchi_rates': '.hisobchi.hisobchi_rates',
    'hisobchi_vision': '.hisobchi.hisobchi_vision',
}

for _mod_name, _mod_path in _MODULE_MAP.items():
    _full_old_name = f'src.services.core.{_mod_name}'
    try:
        _module = importlib.import_module(_mod_path, package=__name__)
        globals()[_mod_name] = _module
        sys.modules[_full_old_name] = _module
    except Exception as e:
        logger.debug(f"Failed to load {_mod_path} for re-export: {e}")
