steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/cloud-run-aiogram.Dockerfile
      - --tag
      - ${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}
images:
  - ${_IMAGE}
