from fastapi import APIRouter, HTTPException, Request
from src.services.core.llm_coach import SalesCoachLLM

router = APIRouter(prefix="/realtime-assist", tags=["realtime-assist"])

@router.post("/tip")
async def realtime_tip(request: Request):
    """Accept a JSON payload with `message` and optional `crm_status`.
    Return a tip generated by the LLM wrapper.
    """
    try:
        payload = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON payload")

    message = payload.get("message")
    crm_status = payload.get("crm_status", "")
    if not message:
        raise HTTPException(status_code=422, detail="`message` is required")

    tip = await SalesCoachLLM.generate_tip(
        transcript=message,
        segments=None,
        context={"crm_status": crm_status},
    )
    if tip is None:
        # fallback to None – caller can handle missing tip
        return {"tip": "", "category": "other"}
    return tip
